FROM mysql

ENV MYSQL_ROOT_PASSWORD=Orion123

# COPY ./test_db /test_db/

ARG USER=sas
ARG UID=1141
ARG GID=1141
ARG PW=Orion123
RUN apt-get update -y \
    && apt-get install -y sudo git unzip wget \
    && useradd -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | chpasswd \
    && usermod -aG sudo sas \
    && wget https://github.com/datacharmer/test_db/archive/master.zip \
    && unzip master.zip 

# WORKDIR /test_db-master

# RUN mysql -u root -p$MYSQL_ROOT_PASSWORD < employees.sql 