FROM jupyterhub/jupyterhub

WORKDIR /shared
COPY requirements.txt ./
ARG USER=sas
ARG UID=1141
ARG GID=1141
ARG PW=Orion123
RUN useradd -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | chpasswd \
    && pip install --no-cache-dir -r requirements.txt 
EXPOSE 8888



